POST http://localhost:3000/login
Content-Type:application/json

{
      "username": "fathia",
      "password": "060899",
      "name": "Fathia",
      "email": "fathia@utem.edu.my"
}

###

GET http://localjost:3000/bye

###

GET http://localhost:3000/